### ISSUE TITLE
Tarballs on releases page

### ISSUE THREAD

**Issue by seleznev** [BonnierNews/logstash_exporter#15]
Hello!

Many other exporters (like [snmp_exporter](https://github.com/prometheus/snmp_exporter/releases), [blackbox_exporter](https://github.com/prometheus/blackbox_exporter/releases), [statsd_exporter](https://github.com/prometheus/statsd_exporter/releases)) has tarballs on releases pages. They can be useful when you don't need a Docker container and do not want to build exporter from sources everytime.

So, it would be great to have tarballs for [releases](https://github.com/BonnierNews/logstash_exporter/releases) (even only `linux-amd64` architecture would be useful).

**Comment by dekhtyarev** [comment]
Hello @christoe ! 

Can you help us with this and PR #14 ?
