### ISSUE TITLE
Add queue metrics

### ISSUE THREAD

**Issue by giskou** [BonnierNews/logstash_exporter#3]
Would be nice to have the queue metrics for persistent queues too.

**Comment by carlpett** [comment]
Hi @giskou!
Could you elaborate? I cannot see anything about queue metrics in the [documentation](https://www.elastic.co/guide/en/logstash/current/monitoring-logstash.html), at least.

**Comment by christoe** [comment]
Hi @giskou! Is it by any chance the "queue_push_duration_in_millis" metric that is of interest to you? If so, that could be arranged.

**Comment by giskou** [comment]
Hello @carlpett!

Sorry for the late reply, but I have been away last week.

I am interested in the [pipeline queue metrics](https://www.elastic.co/guide/en/logstash/current/node-stats-api.html#pipeline-stats).
```
{
  "pipeline" : {
    ...
    "queue" : {
      "events" : 0,
      "type" : "persisted",
      "capacity" : {
        "page_capacity_in_bytes" : 262144000,
        "max_queue_size_in_bytes" : 8589934592,
        "max_unread_events" : 0
      },
      "data" : {
        "path" : "/path/to/data/queue",
        "free_space_in_bytes" : 89280552960,
        "storage_type" : "hfs"
      }
    },
    ...
}
```

**Comment by christoe** [comment]
The latest version of logstash_exporter (c5b2d17) should now expose queue capacity metrics.

**Comment by davidkarlsen** [comment]
Maybe you should start versioning the image? It is really simple to configure docker-hub to build branches and/or tags.
