### ISSUE TITLE
Logstash 6 support

### ISSUE THREAD

**Issue by piotrkochan** [BonnierNews/logstash_exporter#6]
Missing logstash 6 scrapped data

**Comment by christoe** [comment]
Hi @piotrkochan!

Are there metrics available in Logstash 6 that's missing, or is the exporter not compatible with the API in LS6? I haven't had the time to try the LS6 RC yet.

Also, PR:s are very welcome!

**Comment by piotrkochan** [comment]
There was some data missing but I'm not sure about incompatibility

**Comment by christoe** [comment]
@piotrkochan: What metrics are you referring to? I did a quick test with a LS6 container, and there does not seem to be any incompatibilities at least.

**Comment by tgxworld** [comment]
@christoe Dead letter queue metrics would be nice :) Thank you for this exporter.

**Comment by christoe** [comment]
Ok, looking into this a bit more makes me realize that there are incompatibilities with LS6. After introducing multiple pipelines (https://github.com/elastic/logstash/commit/bed8b8a0849f22c323db64b532ab9f7d87388f94) pipeline metrics will not work in the exporter. I will look into the issue.

**Comment by christoe** [comment]
There's a new version/tag available (0.1.1) that should solve the multi-pipeline issue + as a bonus, add DLQ metrics.
